name: foodbite
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  google_sign_in: ^6.3.0
  get: ^4.7.2
  image_picker: ^1.1.2
  shared_preferences: ^2.5.3
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - img/

  fonts:
  - family: Crimson
    fonts:
         - asset: font/CrimsonPro-Regular.ttf
         - asset: font/CrimsonPro-Bold.ttf
         - asset: font/CrimsonPro-Italic.ttf