// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0bdnrS556PKghNNwBupylvy1ZD-fUW3c',
    appId: '1:888405355350:web:d6ccc539537424c76044f7',
    messagingSenderId: '888405355350',
    projectId: 'foodbite-3d993',
    authDomain: 'foodbite-3d993.firebaseapp.com',
    storageBucket: 'foodbite-3d993.firebasestorage.app',
    measurementId: 'G-YB6ESDRKLP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr6wchNFAypMYN7br6RNTZETMWKp9VjDY',
    appId: '1:888405355350:android:406cce687e23b3706044f7',
    messagingSenderId: '888405355350',
    projectId: 'foodbite-3d993',
    storageBucket: 'foodbite-3d993.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv4k6UEQuBzO8Jf85qaYKkffU07WOikIA',
    appId: '1:888405355350:ios:a2134bbc7f5e52c36044f7',
    messagingSenderId: '888405355350',
    projectId: 'foodbite-3d993',
    storageBucket: 'foodbite-3d993.firebasestorage.app',
    iosBundleId: 'com.example.foodbite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBv4k6UEQuBzO8Jf85qaYKkffU07WOikIA',
    appId: '1:888405355350:ios:a2134bbc7f5e52c36044f7',
    messagingSenderId: '888405355350',
    projectId: 'foodbite-3d993',
    storageBucket: 'foodbite-3d993.firebasestorage.app',
    iosBundleId: 'com.example.foodbite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0bdnrS556PKghNNwBupylvy1ZD-fUW3c',
    appId: '1:888405355350:web:b99965146cefb0896044f7',
    messagingSenderId: '888405355350',
    projectId: 'foodbite-3d993',
    authDomain: 'foodbite-3d993.firebaseapp.com',
    storageBucket: 'foodbite-3d993.firebasestorage.app',
    measurementId: 'G-ZT2ERZKNNW',
  );
}
